name: Publish Docker image
on:
  release:
    types: [published]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push_to_registries:
    name: Push Docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: R setup
        uses: r-lib/actions/setup-r@v1
      - name: Build package
        run: R CMD build .
      - name: Push to Docker Hub
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hnskde/qmongr
          tag_with_ref: true
